[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "git+https://github.com/Digital-Pathology/UnifiedImageReader",
    "git+https://github.com/Digital-Pathology/Filtration",
]
build-backend = "setuptools.build_meta"